"""
Database models for security events.
Minimal version using standard sqlite3 (NO aiosqlite).
"""

from datetime import datetime
from typing import Optional

# SQLAlchemy imports - ВСЕ нужные типы здесь
from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Integer,
    String,
    Index,
    create_engine,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session
from sqlalchemy.pool import StaticPool

import os
import logging

logger = logging.getLogger(__name__)
Base = declarative_base()


class SecurityEvent(Base):
    """Represents a security event captured by eBPF agent."""
    __tablename__ = "security_events"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    pid = Column(Integer, nullable=False, index=True)
    uid = Column(Integer, nullable=False, index=True)
    timestamp = Column(BigInteger, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    event_type = Column(Integer, nullable=False)
    filename = Column(String(256), nullable=True)
    dest_ip = Column(String(45), nullable=True)
    dest_port = Column(Integer, nullable=True)
    hostname = Column(String(255), nullable=True, default="unknown")
    agent_version = Column(String(32), nullable=True)
    
    __table_args__ = (
        Index("idx_pid_timestamp", "pid", "timestamp"),
        Index("idx_event_type_created", "event_type", "created_at"),
    )
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "pid": self.pid,
            "uid": self.uid,
            "timestamp": self.timestamp,
            "event_type": self.event_type,
            "filename": self.filename,
            "dest_ip": self.dest_ip,
            "dest_port": self.dest_port,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class Alert(Base):
    """Represents a security alert generated by rule engine."""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, nullable=False, index=True)
    severity = Column(String(16), nullable=False, index=True)
    rule_id = Column(String(64), nullable=False)
    message = Column(String(512), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    is_resolved = Column(Boolean, default=False, index=True)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "event_id": self.event_id,
            "severity": self.severity,
            "rule_id": self.rule_id,
            "message": self.message,
            "created_at": self.created_at.isoformat(),
            "is_resolved": self.is_resolved,
        }


# =============================================================================
# Database Configuration - SIMPLE, NO ASYNC
# =============================================================================

class DatabaseConfig:
    def __init__(self):
        # Используем ТОЛЬКО стандартный sqlite3 - НИКАКОГО +aiosqlite
        self.database_url = "sqlite:///./data/security_events.db"
        self.echo_sql = os.getenv("DB_ECHO", "false").lower() == "true"
    
    def get_engine(self):
        """Create SQLAlchemy engine using standard sqlite3."""
        return create_engine(
            self.database_url,
            connect_args={"check_same_thread": False},
            echo=self.echo_sql,
            poolclass=StaticPool,
        )
    
    def get_sessionmaker(self):
        """Create session factory."""
        engine = self.get_engine()
        return sessionmaker(bind=engine, class_=Session, expire_on_commit=False)


# Global instances
db_config = DatabaseConfig()
SessionLocal = db_config.get_sessionmaker()


def get_db():
    """FastAPI dependency for database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Create all tables if they don't exist."""
    logger.info("Initializing database...")
    engine = db_config.get_engine()
    Base.metadata.create_all(bind=engine)
    logger.info("Database initialized successfully")