"""
Security rule engine for evaluating events and generating alerts.

Rules are designed to be:
- Stateless (for easy horizontal scaling)
- Configurable via environment variables
- Testable in isolation
- Extensible without modifying core logic
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Protocol, List, Dict
import logging
import re
import os

logger = logging.getLogger(__name__)


# =============================================================================
# Domain Types
# =============================================================================

class Severity(Enum):
    """Alert severity levels with numeric priority for sorting."""
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4
    
    def __lt__(self, other):
        return self.value < other.value


@dataclass
class Alert:
    """
    Represents a security alert generated by a rule.
    
    Immutable dataclass ensures thread-safety when rules run concurrently.
    """
    severity: Severity
    message: str
    rule_id: str
    event_id: Optional[int] = None
    metadata: Dict[str, str] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> dict:
        """Serialize for API responses."""
        return {
            "severity": self.severity.name.lower(),
            "message": self.message,
            "rule_id": self.rule_id,
            "event_id": self.event_id,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }


class RuleProtocol(Protocol):
    """
    Protocol defining the interface for security rules.
    
    Using Protocol enables duck-typing while maintaining type safety.
    """
    
    def evaluate(self, event: dict) -> Optional[Alert]:
        """
        Evaluate an event and return an Alert if the rule triggers.
        
        Args:
            event: Dictionary containing event data from eBPF agent
            
        Returns:
            Alert if rule matches, None otherwise
        """
        ...


# =============================================================================
# Base Rule Implementation
# =============================================================================

class BaseRule:
    """
    Base class providing common functionality for rules.
    
    Includes logging, metadata enrichment, and helper methods.
    """
    
    rule_id: str = "base_rule"
    description: str = "Base rule class - should not be used directly"
    
    def __init__(self, enabled: bool = True):
        self.enabled = enabled
        self.logger = logging.getLogger(f"{__name__}.{self.rule_id}")
    
    def evaluate(self, event: dict) -> Optional[Alert]:
        """Template method - delegates to _check() if enabled."""
        if not self.enabled:
            return None
        
        try:
            return self._check(event)
        except Exception as e:
            self.logger.error(f"Rule evaluation failed: {e}", exc_info=True)
            return None
    
    def _check(self, event: dict) -> Optional[Alert]:
        """Override this method in subclasses."""
        raise NotImplementedError
    
    def _create_alert(
        self,
        severity: Severity,
        message: str,
        event: dict,
        **metadata
    ) -> Alert:
        """Helper to create alerts with consistent metadata."""
        return Alert(
            severity=severity,
            message=message,
            rule_id=self.rule_id,
            event_id=event.get("id"),
            metadata={
                "pid": str(event.get("pid")),
                "uid": str(event.get("uid")),
                **metadata
            }
        )


# =============================================================================
# Concrete Rules
# =============================================================================

class SensitiveFileAccessRule(BaseRule):
    """
    Detects access to sensitive system files.
    
    Configurable via SENSITIVE_FILE_PATTERNS env var (comma-separated regex).
    """
    
    rule_id = "sensitive_file_access"
    description = "Alert on access to sensitive files like /etc/shadow"
    
    DEFAULT_PATTERNS = [
        r"^/etc/(shadow|passwd|sudoers|ssh/)",
        r"^/root/\.ssh/",
        r"\.ssh/id_(rsa|ed25519)$",
        r"\.kube/config$",
        r"\.aws/credentials$",
    ]
    
    def __init__(self, enabled: bool = True, patterns: Optional[List[str]] = None):
        super().__init__(enabled)
        
        # Load patterns from env or use defaults
        env_patterns = os.getenv("SENSITIVE_FILE_PATTERNS")
        if env_patterns:
            self.patterns = [p.strip() for p in env_patterns.split(",") if p.strip()]
        else:
            self.patterns = patterns or self.DEFAULT_PATTERNS
        
        # Pre-compile regex for performance
        self.compiled_patterns = [re.compile(p, re.IGNORECASE) for p in self.patterns]
    
    def _check(self, event: dict) -> Optional[Alert]:
        # Only evaluate file events
        if event.get("event_type") != 1:  # EVENT_FILE_OPEN
            return None
        
        filename = event.get("filename", "")
        if not filename:
            return None
        
        for pattern in self.compiled_patterns:
            if pattern.search(filename):
                uid = event.get("uid", -1)
                
                # Higher severity for root accessing sensitive files
                if uid == 0:
                    severity = Severity.CRITICAL
                    message = f"Root accessed sensitive file: {filename}"
                else:
                    severity = Severity.HIGH
                    message = f"Non-root user accessed sensitive file: {filename}"
                
                self.logger.info(f"Rule triggered: {message}")
                return self._create_alert(severity, message, event, filename=filename)
        
        return None


class SuspiciousPortRule(BaseRule):
    """
    Detects connections to known malicious or suspicious ports.
    
    Port lists can be extended via SUSPICIOUS_PORTS env var.
    """
    
    rule_id = "suspicious_port"
    description = "Alert on connections to suspicious ports"
    
    # Common backdoor/C2 ports
    DEFAULT_PORTS = {
        4444,   # Metasploit default
        5555,   # Android debug / backdoor
        6666,   # IRC backdoor
        31337,  # "Elite" hacker port
        12345,  # NetBus
        1234,   # Common test backdoor
        65535,  # Often used in exploits
    }
    
    def __init__(self, enabled: bool = True, ports: Optional[set] = None):
        super().__init__(enabled)
        
        # Load from env: SUSPICIOUS_PORTS=4444,5555,9999
        env_ports = os.getenv("SUSPICIOUS_PORTS")
        if env_ports:
            try:
                self.ports = {int(p.strip()) for p in env_ports.split(",") if p.strip()}
            except ValueError:
                logger.warning(f"Invalid SUSPICIOUS_PORTS format: {env_ports}")
                self.ports = self.DEFAULT_PORTS
        else:
            self.ports = ports or self.DEFAULT_PORTS
    
    def _check(self, event: dict) -> Optional[Alert]:
        # Only evaluate network events
        if event.get("event_type") != 2:  # EVENT_NETWORK_CONNECT
            return None
        
        port = event.get("dest_port")
        if port is None or port not in self.ports:
            return None
        
        dest_ip = event.get("dest_ip", "unknown")
        pid = event.get("pid", "unknown")
        
        message = f"Process {pid} connected to suspicious port {port} on {dest_ip}"
        
        self.logger.warning(f"Rule triggered: {message}")
        return self._create_alert(
            Severity.CRITICAL,
            message,
            event,
            dest_ip=dest_ip,
            dest_port=str(port)
        )


class RootActivityRule(BaseRule):
    """
    Monitors activity from root user (UID 0).
    
    Not all root activity is malicious, so this generates MEDIUM severity
    alerts for audit purposes rather than immediate blocking.
    """
    
    rule_id = "root_activity"
    description = "Log significant activity from root user"
    
    # Only alert on these event types to reduce noise
    MONITORED_TYPES = {1, 2}  # FileOpen, NetworkConnect
    
    def __init__(self, enabled: bool = True, exclude_paths: Optional[List[str]] = None):
        super().__init__(enabled)
        self.exclude_paths = exclude_paths or ["/proc/", "/sys/"]
    
    def _check(self, event: dict) -> Optional[Alert]:
        # Only evaluate if UID is root
        if event.get("uid") != 0:
            return None
        
        # Filter by event type
        if event.get("event_type") not in self.MONITORED_TYPES:
            return None
        
        # Exclude noisy paths
        filename = event.get("filename", "")
        if any(filename.startswith(excl) for excl in self.exclude_paths):
            return None
        
        event_type = event.get("event_type")
        target = filename or f"{event.get('dest_ip')}:{event.get('dest_port')}"
        
        message = f"Root activity: {'file access' if event_type == 1 else 'network connection'} to {target}"
        
        # Debug-level logging to avoid spam
        self.logger.debug(f"Rule triggered: {message}")
        return self._create_alert(
            Severity.MEDIUM,
            message,
            event,
            target=target
        )


class ExecutableWriteRule(BaseRule):
    """
    Detects writes to executable paths (potential malware drop).
    
    Uses simple path heuristics - can be extended with file hash checking.
    """
    
    rule_id = "executable_write"
    description = "Alert on writes to executable directories"
    
    EXECUTABLE_DIRS = [
        "/usr/bin", "/usr/sbin", "/usr/local/bin",
        "/bin", "/sbin",
        "/opt/",
    ]
    
    EXECUTABLE_EXTENSIONS = {".sh", ".py", ".pl", ".rb", ".so", ".ko"}
    
    def _check(self, event: dict) -> Optional[Alert]:
        if event.get("event_type") != 1:
            return None
        
        filename = event.get("filename", "")
        if not filename:
            return None
        
        # Check if writing to executable directory
        is_exec_dir = any(filename.startswith(d) for d in self.EXECUTABLE_DIRS)
        
        # Check if file has executable extension
        has_exec_ext = any(filename.endswith(ext) for ext in self.EXECUTABLE_EXTENSIONS)
        
        if is_exec_dir or has_exec_ext:
            message = f"Write to executable path: {filename}"
            severity = Severity.HIGH if is_exec_dir else Severity.MEDIUM
            
            self.logger.info(f"Rule triggered: {message}")
            return self._create_alert(severity, message, event, filename=filename)
        
        return None


# =============================================================================
# Rule Engine
# =============================================================================

class RuleEngine:
    """
    Orchestrates rule evaluation for incoming events.
    
    Thread-safe and designed for concurrent evaluation.
    """
    
    def __init__(self, rules: Optional[List[RuleProtocol]] = None):
        """
        Initialize with default rules or custom list.
        
        Args:
            rules: Optional list of RuleProtocol instances.
                  If None, loads default rules from environment.
        """
        self.rules = rules or self._load_default_rules()
        self.logger = logging.getLogger(__name__)
        self.logger.info(f"Initialized RuleEngine with {len(self.rules)} rules")
    
    def _load_default_rules(self) -> List[RuleProtocol]:
        """Load default rules with environment-based configuration."""
        return [
            SensitiveFileAccessRule(),
            SuspiciousPortRule(),
            RootActivityRule(),
            ExecutableWriteRule(),
        ]
    
    def evaluate(self, event: dict) -> List[Alert]:
        """
        Evaluate an event against all enabled rules.
        
        Args:
            event: Event dictionary from eBPF agent
            
        Returns:
            List of triggered alerts (may be empty)
        """
        alerts = []
        
        for rule in self.rules:
            try:
                alert = rule.evaluate(event)
                if alert:
                    alerts.append(alert)
            except Exception as e:
                self.logger.error(
                    f"Unhandled error in rule {rule.rule_id}: {e}",
                    exc_info=True
                )
                # Continue evaluating other rules - don't let one failure block all
        
        return alerts
    
    def get_rule_info(self) -> List[dict]:
        """Return metadata about loaded rules for API documentation."""
        return [
            {
                "rule_id": rule.rule_id,
                "description": getattr(rule, "description", "No description"),
                "enabled": getattr(rule, "enabled", True),
            }
            for rule in self.rules
        ]
    
    def enable_rule(self, rule_id: str) -> bool:
        """Enable a rule by ID. Returns True if found."""
        for rule in self.rules:
            if rule.rule_id == rule_id:
                rule.enabled = True
                self.logger.info(f"Enabled rule: {rule_id}")
                return True
        return False
    
    def disable_rule(self, rule_id: str) -> bool:
        """Disable a rule by ID. Returns True if found."""
        for rule in self.rules:
            if rule.rule_id == rule_id:
                rule.enabled = False
                self.logger.info(f"Disabled rule: {rule_id}")
                return True
        return False


# Global instance for dependency injection
rule_engine = RuleEngine()